//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDSEntities1 : DbContext
    {
        public EDSEntities1()
            : base("name=EDSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<police> police { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<ambulance> ambulances { get; set; }
        public virtual DbSet<bombdisposal> bombdisposals { get; set; }
        public virtual DbSet<coastguard> coastguards { get; set; }
        public virtual DbSet<fireservice> fireservices { get; set; }
        public virtual DbSet<towservice> towservices { get; set; }
    }
}
