//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
        public int ps_id { get; set; }
        public int h_id { get; set; }
        public Nullable<int> fs_id { get; set; }
        public Nullable<int> a_id { get; set; }
        public Nullable<int> t_id { get; set; }
        public Nullable<int> cg_id { get; set; }
        public Nullable<int> bd_id { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual police police { get; set; }
        public virtual ambulance ambulance { get; set; }
        public virtual bombdisposal bombdisposal { get; set; }
        public virtual coastguard coastguard { get; set; }
        public virtual fireservice fireservice { get; set; }
        public virtual towservice towservice { get; set; }
    }
}
